README.md, requirements.txt
Updated README with a link to Adapt site for more in-depth examples and documentation.
=> Readme documentation

adapt/engine.py
My git branch was rather messed up so I just started a new one.
This is all the code from "https://github.com/MycroftAI/adapt/pull/24" just in a format that can be merged without issues.
=> Added DomainIntentEngine

examples/multi_domain_intent_parser.py, test/DomainIntentEngineTest.py
When I created the new fork to fix my messed up repo I forgot to add in the tests and example from the old code.
=> Added back tests and example.

adapt/intent.py, setup.py, test/IntentTest.py
Bug where one_of is not recognized as first token in utterance.
=> Adding a new test to fix bug

adapt/context.py, adapt/engine.py, adapt/entity_tagger.py, adapt/expander.py, adapt/intent.py, adapt/parser.py, adapt/tools/text/tokenizer.py, adapt/tools/text/trie.py
This is just the new doc strings generated from  my debug and testing efforts.
Signed-off-by: Art McGee <amcgee7@jaguarlandrover.com>
=> added code comments

README.md
This prettifies the formatting of the example snippets.
Nothing to test. 
Nope, but change is so minor that i doubt it even matters (Formatting changes aren't even something you can hold copyrights on)
=> Set formating of example to right language

README.md
- Add standard repo badges
- Remove Waffle badge
- Move description to top
- Add embedded video of Adapt overview
CLA (Contributor Licensing Agreement)
=> Update Adapt README

adapt/intent.py, setup.py, test/IntentTest.py
Fixes https://github.com/MycroftAI/adapt/issues/91
=> Change [] to ()

adapt/engine.py
Fixes typos in some Engine's docstrings
Nothing (Pure documentation change)
Sent!
=> Update engine.py (fix typos in docstring)

README.md
adapt.mycroft.ai seems to be down.
Yes
=> Change the URL for more docs

adapt/engine.py, adapt/parser.py, requirements.txt, setup.py
Updates the pyee module to the latest version. A change is prepared for mycroft-core updating this as well.
The code changes the now deprecated pyee.EventEmitter to the equivalent pyee.BaseEventEmitter
=> Upgrade to the latest version of pyee

adapt/intent.py, adapt/tools/text/trie.py
Fixes a small typo in a couple files' docstrings.
=> Chore: fix 'weather' -> 'whether' typo.

examples/multi_domain_intent_parser.py, examples/multi_intent_parser.py
Fixes Issue #109 
Run tests from command line
Yes
=> Issues/109: Confusing examples

adapt/engine.py, adapt/parser.py, requirements.txt, setup.py
Update the pyee requirement to 8.1.0, this version adds some thread safety features which isn't so much needed for the adapt use case but may have impacts on Mycroft-core.
=> Update to pyee 8.1.0

.travis.yml, setup.py
Set travis to run tests on python 3.9 as well
=> Add python 3.9 to test suite

adapt/context.py, test/ContextManagerTest.py
Fixes #97 
Added unit tests for ContextManagerFrame.metadata_matches` and `ContextManagerFrame.merge_context`
Signed
=> Fix ContextManagerFrame.merge_context

adapt/tools/text/trie.py
Fixes #111 
Docstring change only.
Yes
=> Fix docstrings per #111

adapt/context.py, setup.py
* Fixes issue #55 
Passes existing tests.
Yes
=> Fix unsafe defaults in context

adapt/context.py, adapt/engine.py, adapt/tools/debug/__init__.py, adapt/tools/text/tokenizer.py
Docstring updates, per #130. 
Docstring updates only.
yes
=> Docstring updates

setup.py
Bump version to 1.0.0 and mark as stable.
No logical changes.
yes
=> Bump version to 1.0.0 and mark stable.

setup.py
Fixes failed upload from #151 
None
yes
=> Use correct classifier
